INSERT INTO zodiacs (zodiac, description) VALUES 
('Capricorn', 'Determined, goal-oriented, and unforgiving, people under the Capricorn sign tend to listen to music that captures their level of discipline. They tend to listen to rock or classical music'),
('Aquarius', 'Wise, inventive, introverted, and ambitious, people under the Aquarius sign tend to be forward-thinking and innovative. They tend to listen to trendy or punk music.'),
('Pisces', 'Playful, kind, imaginative, and nurturing, people under the Pisces sign are creative and introspective. They tend to listen to relaxing or indie music.'),
('Aries', 'Competitive, tenacious, and self-aware, people under the Aries sign are assertive and bold. They tend to listen to metal and hip hop or rap music.'),
('Taurus', 'Loyal and reliable, people under the Taurus sign are often connected with nature and their senses. They tend to listen to country or R&B music.'),
('Gemini', 'Adaptive and short tempered, people under the Gemini sign are often very flexible and listen to music that is diverse. They tend to listen to EDM or music from other media.'),
('Cancer', 'Passionate, loyal, and selfless, people under the Cancer sign are often sentimental and nostalgic. They tend to listen to folk or romantic music.'),
('Leo', 'Confident and loyal to themselves, people under the Leo sign tend to like being in the spotlight. They often like trendy or pop music.'),
('Virgo', 'Perfectionist, diligent, and organized, people under the Virgo sign tend to be crafty and pay close attention to detail. They often listen to instrumental or classsical music.'),
('Libra', 'Empathetic, comforting, and unconfrontational, people under the Libra sign tend to love balance and harmony. They tend to like alternative or pop music.'),
('Scorpio', 'Intense and wild, people under the Scorpio sign tend to have great depth of emotion. They tend to listen to soul or metal music.'),
('Sagittarius', 'Spontaneous and entertaining, people under the Sagittarius sign love to explore and break boundaries. They often listen to alternative or rock music.');


INSERT INTO genres (genreName, topzodiac, secondzodiac) VALUES 
('hip hop rap', 'Scorpio', 'Aries'),
('pop', 'Libra', 'Leo'),
('country', 'Taurus', 'Cancer'),
('rock', 'Capricorn', 'Sagittarius'),
('edm', 'Aquarius', 'Gemini'),
('indie', 'Pisces', 'Virgo'),
('jazz', 'Gemini', 'Scorpio'),
('classical', 'Virgo', 'Capricorn'),
('r&b', 'Cancer', 'Taurus'),
('punk', 'Aries', 'Aquarius'),
('alternative', 'Sagittarius', 'Libra'),
('folk', 'Cancer', 'Scorpio'),
('tv & films', 'Gemini', 'Sagittarius'),
('chill', 'Pisces', 'Libra'),
('trending', 'Leo', 'Aquarius'),
('soul', 'Scorpio', 'Cancer'),
('ambient', 'Pisces', 'Libra'),
('love', 'Cancer', 'Libra'),
('metal', 'Scorpio', 'Aries'),
('instrumental', 'Virgo', 'Aquarius');